name: Publish Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    uses: Coongro/plugin-ci/.github/workflows/plugin-publish.yml@main
    secrets: inherit
    permissions:
      contents: write
